### ISSUE TITLE
What happened to Vundle

### ISSUE THREAD

**Issue by gustafbstrom** [mckellygit/Vundle.vim#1]
Hello,
This is not as much a bug report as general question: what happened to the original Vundle repo? It seems like it disappeared from one day to another without any trace?

**Comment by mckellygit** [comment]
Hi,
I have no idea what happened to the Vundle.vim repo on github.  Like you, I was surprised to suddenly find it missing.  I pushed this copy to github, just to have it there.
I will look to transition to vim-plug soon.

**Comment by gustafbstrom** [comment]
OK. Will hopefully hear more soon and hope that their user base won't be decimated, have been happy with this plugin so far. That said: will look into vim-plug until then.
